package com.qccr.sh.domain;

public class Code extends CodeKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sh_code.codename
     *
     * @mbggenerated
     */
    private String codename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sh_code.codeorder
     *
     * @mbggenerated
     */
    private Integer codeorder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sh_code.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sh_code.is_delete
     *
     * @mbggenerated
     */
    private Boolean isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sh_code.codename
     *
     * @return the value of sh_code.codename
     *
     * @mbggenerated
     */
    public String getCodename() {
        return codename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sh_code.codename
     *
     * @param codename the value for sh_code.codename
     *
     * @mbggenerated
     */
    public void setCodename(String codename) {
        this.codename = codename == null ? null : codename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sh_code.codeorder
     *
     * @return the value of sh_code.codeorder
     *
     * @mbggenerated
     */
    public Integer getCodeorder() {
        return codeorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sh_code.codeorder
     *
     * @param codeorder the value for sh_code.codeorder
     *
     * @mbggenerated
     */
    public void setCodeorder(Integer codeorder) {
        this.codeorder = codeorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sh_code.remark
     *
     * @return the value of sh_code.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sh_code.remark
     *
     * @param remark the value for sh_code.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sh_code.is_delete
     *
     * @return the value of sh_code.is_delete
     *
     * @mbggenerated
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sh_code.is_delete
     *
     * @param isDelete the value for sh_code.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }
}