package com.qccr.sh.domain;

public class Config {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sh_conf.ck
     *
     * @mbggenerated
     */
    private String ck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sh_conf.cv
     *
     * @mbggenerated
     */
    private String cv;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sh_conf.ck
     *
     * @return the value of sh_conf.ck
     *
     * @mbggenerated
     */
    public String getCk() {
        return ck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sh_conf.ck
     *
     * @param ck the value for sh_conf.ck
     *
     * @mbggenerated
     */
    public void setCk(String ck) {
        this.ck = ck == null ? null : ck.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sh_conf.cv
     *
     * @return the value of sh_conf.cv
     *
     * @mbggenerated
     */
    public String getCv() {
        return cv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sh_conf.cv
     *
     * @param cv the value for sh_conf.cv
     *
     * @mbggenerated
     */
    public void setCv(String cv) {
        this.cv = cv == null ? null : cv.trim();
    }
}