package com.qccr.sh.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OrderServerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_server
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_server
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_server
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_server
     *
     * @mbggenerated
     */
    public OrderServerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_server
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_server
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_server
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_server
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_server
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_server
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_server
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_server
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_server
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_server
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_server
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(Long value) {
            addCriterion("order_id =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(Long value) {
            addCriterion("order_id <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(Long value) {
            addCriterion("order_id >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(Long value) {
            addCriterion("order_id >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(Long value) {
            addCriterion("order_id <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(Long value) {
            addCriterion("order_id <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<Long> values) {
            addCriterion("order_id in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<Long> values) {
            addCriterion("order_id not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(Long value1, Long value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(Long value1, Long value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsIdIsNull() {
            addCriterion("order_goods_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsIdIsNotNull() {
            addCriterion("order_goods_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsIdEqualTo(Long value) {
            addCriterion("order_goods_id =", value, "orderGoodsId");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsIdNotEqualTo(Long value) {
            addCriterion("order_goods_id <>", value, "orderGoodsId");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsIdGreaterThan(Long value) {
            addCriterion("order_goods_id >", value, "orderGoodsId");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsIdGreaterThanOrEqualTo(Long value) {
            addCriterion("order_goods_id >=", value, "orderGoodsId");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsIdLessThan(Long value) {
            addCriterion("order_goods_id <", value, "orderGoodsId");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsIdLessThanOrEqualTo(Long value) {
            addCriterion("order_goods_id <=", value, "orderGoodsId");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsIdIn(List<Long> values) {
            addCriterion("order_goods_id in", values, "orderGoodsId");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsIdNotIn(List<Long> values) {
            addCriterion("order_goods_id not in", values, "orderGoodsId");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsIdBetween(Long value1, Long value2) {
            addCriterion("order_goods_id between", value1, value2, "orderGoodsId");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsIdNotBetween(Long value1, Long value2) {
            addCriterion("order_goods_id not between", value1, value2, "orderGoodsId");
            return (Criteria) this;
        }

        public Criteria andStoreIdIsNull() {
            addCriterion("store_id is null");
            return (Criteria) this;
        }

        public Criteria andStoreIdIsNotNull() {
            addCriterion("store_id is not null");
            return (Criteria) this;
        }

        public Criteria andStoreIdEqualTo(Integer value) {
            addCriterion("store_id =", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdNotEqualTo(Integer value) {
            addCriterion("store_id <>", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdGreaterThan(Integer value) {
            addCriterion("store_id >", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("store_id >=", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdLessThan(Integer value) {
            addCriterion("store_id <", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdLessThanOrEqualTo(Integer value) {
            addCriterion("store_id <=", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdIn(List<Integer> values) {
            addCriterion("store_id in", values, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdNotIn(List<Integer> values) {
            addCriterion("store_id not in", values, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdBetween(Integer value1, Integer value2) {
            addCriterion("store_id between", value1, value2, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdNotBetween(Integer value1, Integer value2) {
            addCriterion("store_id not between", value1, value2, "storeId");
            return (Criteria) this;
        }

        public Criteria andClearIdIsNull() {
            addCriterion("clear_id is null");
            return (Criteria) this;
        }

        public Criteria andClearIdIsNotNull() {
            addCriterion("clear_id is not null");
            return (Criteria) this;
        }

        public Criteria andClearIdEqualTo(Integer value) {
            addCriterion("clear_id =", value, "clearId");
            return (Criteria) this;
        }

        public Criteria andClearIdNotEqualTo(Integer value) {
            addCriterion("clear_id <>", value, "clearId");
            return (Criteria) this;
        }

        public Criteria andClearIdGreaterThan(Integer value) {
            addCriterion("clear_id >", value, "clearId");
            return (Criteria) this;
        }

        public Criteria andClearIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("clear_id >=", value, "clearId");
            return (Criteria) this;
        }

        public Criteria andClearIdLessThan(Integer value) {
            addCriterion("clear_id <", value, "clearId");
            return (Criteria) this;
        }

        public Criteria andClearIdLessThanOrEqualTo(Integer value) {
            addCriterion("clear_id <=", value, "clearId");
            return (Criteria) this;
        }

        public Criteria andClearIdIn(List<Integer> values) {
            addCriterion("clear_id in", values, "clearId");
            return (Criteria) this;
        }

        public Criteria andClearIdNotIn(List<Integer> values) {
            addCriterion("clear_id not in", values, "clearId");
            return (Criteria) this;
        }

        public Criteria andClearIdBetween(Integer value1, Integer value2) {
            addCriterion("clear_id between", value1, value2, "clearId");
            return (Criteria) this;
        }

        public Criteria andClearIdNotBetween(Integer value1, Integer value2) {
            addCriterion("clear_id not between", value1, value2, "clearId");
            return (Criteria) this;
        }

        public Criteria andServerStoreIdIsNull() {
            addCriterion("server_store_id is null");
            return (Criteria) this;
        }

        public Criteria andServerStoreIdIsNotNull() {
            addCriterion("server_store_id is not null");
            return (Criteria) this;
        }

        public Criteria andServerStoreIdEqualTo(Integer value) {
            addCriterion("server_store_id =", value, "serverStoreId");
            return (Criteria) this;
        }

        public Criteria andServerStoreIdNotEqualTo(Integer value) {
            addCriterion("server_store_id <>", value, "serverStoreId");
            return (Criteria) this;
        }

        public Criteria andServerStoreIdGreaterThan(Integer value) {
            addCriterion("server_store_id >", value, "serverStoreId");
            return (Criteria) this;
        }

        public Criteria andServerStoreIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("server_store_id >=", value, "serverStoreId");
            return (Criteria) this;
        }

        public Criteria andServerStoreIdLessThan(Integer value) {
            addCriterion("server_store_id <", value, "serverStoreId");
            return (Criteria) this;
        }

        public Criteria andServerStoreIdLessThanOrEqualTo(Integer value) {
            addCriterion("server_store_id <=", value, "serverStoreId");
            return (Criteria) this;
        }

        public Criteria andServerStoreIdIn(List<Integer> values) {
            addCriterion("server_store_id in", values, "serverStoreId");
            return (Criteria) this;
        }

        public Criteria andServerStoreIdNotIn(List<Integer> values) {
            addCriterion("server_store_id not in", values, "serverStoreId");
            return (Criteria) this;
        }

        public Criteria andServerStoreIdBetween(Integer value1, Integer value2) {
            addCriterion("server_store_id between", value1, value2, "serverStoreId");
            return (Criteria) this;
        }

        public Criteria andServerStoreIdNotBetween(Integer value1, Integer value2) {
            addCriterion("server_store_id not between", value1, value2, "serverStoreId");
            return (Criteria) this;
        }

        public Criteria andServerNameIsNull() {
            addCriterion("server_name is null");
            return (Criteria) this;
        }

        public Criteria andServerNameIsNotNull() {
            addCriterion("server_name is not null");
            return (Criteria) this;
        }

        public Criteria andServerNameEqualTo(String value) {
            addCriterion("server_name =", value, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerNameNotEqualTo(String value) {
            addCriterion("server_name <>", value, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerNameGreaterThan(String value) {
            addCriterion("server_name >", value, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerNameGreaterThanOrEqualTo(String value) {
            addCriterion("server_name >=", value, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerNameLessThan(String value) {
            addCriterion("server_name <", value, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerNameLessThanOrEqualTo(String value) {
            addCriterion("server_name <=", value, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerNameLike(String value) {
            addCriterion("server_name like", value, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerNameNotLike(String value) {
            addCriterion("server_name not like", value, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerNameIn(List<String> values) {
            addCriterion("server_name in", values, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerNameNotIn(List<String> values) {
            addCriterion("server_name not in", values, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerNameBetween(String value1, String value2) {
            addCriterion("server_name between", value1, value2, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerNameNotBetween(String value1, String value2) {
            addCriterion("server_name not between", value1, value2, "serverName");
            return (Criteria) this;
        }

        public Criteria andAppointTimeIsNull() {
            addCriterion("appoint_time is null");
            return (Criteria) this;
        }

        public Criteria andAppointTimeIsNotNull() {
            addCriterion("appoint_time is not null");
            return (Criteria) this;
        }

        public Criteria andAppointTimeEqualTo(Date value) {
            addCriterion("appoint_time =", value, "appointTime");
            return (Criteria) this;
        }

        public Criteria andAppointTimeNotEqualTo(Date value) {
            addCriterion("appoint_time <>", value, "appointTime");
            return (Criteria) this;
        }

        public Criteria andAppointTimeGreaterThan(Date value) {
            addCriterion("appoint_time >", value, "appointTime");
            return (Criteria) this;
        }

        public Criteria andAppointTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("appoint_time >=", value, "appointTime");
            return (Criteria) this;
        }

        public Criteria andAppointTimeLessThan(Date value) {
            addCriterion("appoint_time <", value, "appointTime");
            return (Criteria) this;
        }

        public Criteria andAppointTimeLessThanOrEqualTo(Date value) {
            addCriterion("appoint_time <=", value, "appointTime");
            return (Criteria) this;
        }

        public Criteria andAppointTimeIn(List<Date> values) {
            addCriterion("appoint_time in", values, "appointTime");
            return (Criteria) this;
        }

        public Criteria andAppointTimeNotIn(List<Date> values) {
            addCriterion("appoint_time not in", values, "appointTime");
            return (Criteria) this;
        }

        public Criteria andAppointTimeBetween(Date value1, Date value2) {
            addCriterion("appoint_time between", value1, value2, "appointTime");
            return (Criteria) this;
        }

        public Criteria andAppointTimeNotBetween(Date value1, Date value2) {
            addCriterion("appoint_time not between", value1, value2, "appointTime");
            return (Criteria) this;
        }

        public Criteria andOrigCostIsNull() {
            addCriterion("orig_cost is null");
            return (Criteria) this;
        }

        public Criteria andOrigCostIsNotNull() {
            addCriterion("orig_cost is not null");
            return (Criteria) this;
        }

        public Criteria andOrigCostEqualTo(BigDecimal value) {
            addCriterion("orig_cost =", value, "origCost");
            return (Criteria) this;
        }

        public Criteria andOrigCostNotEqualTo(BigDecimal value) {
            addCriterion("orig_cost <>", value, "origCost");
            return (Criteria) this;
        }

        public Criteria andOrigCostGreaterThan(BigDecimal value) {
            addCriterion("orig_cost >", value, "origCost");
            return (Criteria) this;
        }

        public Criteria andOrigCostGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("orig_cost >=", value, "origCost");
            return (Criteria) this;
        }

        public Criteria andOrigCostLessThan(BigDecimal value) {
            addCriterion("orig_cost <", value, "origCost");
            return (Criteria) this;
        }

        public Criteria andOrigCostLessThanOrEqualTo(BigDecimal value) {
            addCriterion("orig_cost <=", value, "origCost");
            return (Criteria) this;
        }

        public Criteria andOrigCostIn(List<BigDecimal> values) {
            addCriterion("orig_cost in", values, "origCost");
            return (Criteria) this;
        }

        public Criteria andOrigCostNotIn(List<BigDecimal> values) {
            addCriterion("orig_cost not in", values, "origCost");
            return (Criteria) this;
        }

        public Criteria andOrigCostBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("orig_cost between", value1, value2, "origCost");
            return (Criteria) this;
        }

        public Criteria andOrigCostNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("orig_cost not between", value1, value2, "origCost");
            return (Criteria) this;
        }

        public Criteria andRealCostIsNull() {
            addCriterion("real_cost is null");
            return (Criteria) this;
        }

        public Criteria andRealCostIsNotNull() {
            addCriterion("real_cost is not null");
            return (Criteria) this;
        }

        public Criteria andRealCostEqualTo(BigDecimal value) {
            addCriterion("real_cost =", value, "realCost");
            return (Criteria) this;
        }

        public Criteria andRealCostNotEqualTo(BigDecimal value) {
            addCriterion("real_cost <>", value, "realCost");
            return (Criteria) this;
        }

        public Criteria andRealCostGreaterThan(BigDecimal value) {
            addCriterion("real_cost >", value, "realCost");
            return (Criteria) this;
        }

        public Criteria andRealCostGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("real_cost >=", value, "realCost");
            return (Criteria) this;
        }

        public Criteria andRealCostLessThan(BigDecimal value) {
            addCriterion("real_cost <", value, "realCost");
            return (Criteria) this;
        }

        public Criteria andRealCostLessThanOrEqualTo(BigDecimal value) {
            addCriterion("real_cost <=", value, "realCost");
            return (Criteria) this;
        }

        public Criteria andRealCostIn(List<BigDecimal> values) {
            addCriterion("real_cost in", values, "realCost");
            return (Criteria) this;
        }

        public Criteria andRealCostNotIn(List<BigDecimal> values) {
            addCriterion("real_cost not in", values, "realCost");
            return (Criteria) this;
        }

        public Criteria andRealCostBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("real_cost between", value1, value2, "realCost");
            return (Criteria) this;
        }

        public Criteria andRealCostNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("real_cost not between", value1, value2, "realCost");
            return (Criteria) this;
        }

        public Criteria andSmsCodeIsNull() {
            addCriterion("sms_code is null");
            return (Criteria) this;
        }

        public Criteria andSmsCodeIsNotNull() {
            addCriterion("sms_code is not null");
            return (Criteria) this;
        }

        public Criteria andSmsCodeEqualTo(String value) {
            addCriterion("sms_code =", value, "smsCode");
            return (Criteria) this;
        }

        public Criteria andSmsCodeNotEqualTo(String value) {
            addCriterion("sms_code <>", value, "smsCode");
            return (Criteria) this;
        }

        public Criteria andSmsCodeGreaterThan(String value) {
            addCriterion("sms_code >", value, "smsCode");
            return (Criteria) this;
        }

        public Criteria andSmsCodeGreaterThanOrEqualTo(String value) {
            addCriterion("sms_code >=", value, "smsCode");
            return (Criteria) this;
        }

        public Criteria andSmsCodeLessThan(String value) {
            addCriterion("sms_code <", value, "smsCode");
            return (Criteria) this;
        }

        public Criteria andSmsCodeLessThanOrEqualTo(String value) {
            addCriterion("sms_code <=", value, "smsCode");
            return (Criteria) this;
        }

        public Criteria andSmsCodeLike(String value) {
            addCriterion("sms_code like", value, "smsCode");
            return (Criteria) this;
        }

        public Criteria andSmsCodeNotLike(String value) {
            addCriterion("sms_code not like", value, "smsCode");
            return (Criteria) this;
        }

        public Criteria andSmsCodeIn(List<String> values) {
            addCriterion("sms_code in", values, "smsCode");
            return (Criteria) this;
        }

        public Criteria andSmsCodeNotIn(List<String> values) {
            addCriterion("sms_code not in", values, "smsCode");
            return (Criteria) this;
        }

        public Criteria andSmsCodeBetween(String value1, String value2) {
            addCriterion("sms_code between", value1, value2, "smsCode");
            return (Criteria) this;
        }

        public Criteria andSmsCodeNotBetween(String value1, String value2) {
            addCriterion("sms_code not between", value1, value2, "smsCode");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Byte value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Byte value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Byte value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Byte value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Byte value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Byte> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Byte> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Byte value1, Byte value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andSmsTimeIsNull() {
            addCriterion("sms_time is null");
            return (Criteria) this;
        }

        public Criteria andSmsTimeIsNotNull() {
            addCriterion("sms_time is not null");
            return (Criteria) this;
        }

        public Criteria andSmsTimeEqualTo(Date value) {
            addCriterion("sms_time =", value, "smsTime");
            return (Criteria) this;
        }

        public Criteria andSmsTimeNotEqualTo(Date value) {
            addCriterion("sms_time <>", value, "smsTime");
            return (Criteria) this;
        }

        public Criteria andSmsTimeGreaterThan(Date value) {
            addCriterion("sms_time >", value, "smsTime");
            return (Criteria) this;
        }

        public Criteria andSmsTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("sms_time >=", value, "smsTime");
            return (Criteria) this;
        }

        public Criteria andSmsTimeLessThan(Date value) {
            addCriterion("sms_time <", value, "smsTime");
            return (Criteria) this;
        }

        public Criteria andSmsTimeLessThanOrEqualTo(Date value) {
            addCriterion("sms_time <=", value, "smsTime");
            return (Criteria) this;
        }

        public Criteria andSmsTimeIn(List<Date> values) {
            addCriterion("sms_time in", values, "smsTime");
            return (Criteria) this;
        }

        public Criteria andSmsTimeNotIn(List<Date> values) {
            addCriterion("sms_time not in", values, "smsTime");
            return (Criteria) this;
        }

        public Criteria andSmsTimeBetween(Date value1, Date value2) {
            addCriterion("sms_time between", value1, value2, "smsTime");
            return (Criteria) this;
        }

        public Criteria andSmsTimeNotBetween(Date value1, Date value2) {
            addCriterion("sms_time not between", value1, value2, "smsTime");
            return (Criteria) this;
        }

        public Criteria andRefundSumIsNull() {
            addCriterion("refund_sum is null");
            return (Criteria) this;
        }

        public Criteria andRefundSumIsNotNull() {
            addCriterion("refund_sum is not null");
            return (Criteria) this;
        }

        public Criteria andRefundSumEqualTo(BigDecimal value) {
            addCriterion("refund_sum =", value, "refundSum");
            return (Criteria) this;
        }

        public Criteria andRefundSumNotEqualTo(BigDecimal value) {
            addCriterion("refund_sum <>", value, "refundSum");
            return (Criteria) this;
        }

        public Criteria andRefundSumGreaterThan(BigDecimal value) {
            addCriterion("refund_sum >", value, "refundSum");
            return (Criteria) this;
        }

        public Criteria andRefundSumGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("refund_sum >=", value, "refundSum");
            return (Criteria) this;
        }

        public Criteria andRefundSumLessThan(BigDecimal value) {
            addCriterion("refund_sum <", value, "refundSum");
            return (Criteria) this;
        }

        public Criteria andRefundSumLessThanOrEqualTo(BigDecimal value) {
            addCriterion("refund_sum <=", value, "refundSum");
            return (Criteria) this;
        }

        public Criteria andRefundSumIn(List<BigDecimal> values) {
            addCriterion("refund_sum in", values, "refundSum");
            return (Criteria) this;
        }

        public Criteria andRefundSumNotIn(List<BigDecimal> values) {
            addCriterion("refund_sum not in", values, "refundSum");
            return (Criteria) this;
        }

        public Criteria andRefundSumBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("refund_sum between", value1, value2, "refundSum");
            return (Criteria) this;
        }

        public Criteria andRefundSumNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("refund_sum not between", value1, value2, "refundSum");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andKfNoteIsNull() {
            addCriterion("kf_note is null");
            return (Criteria) this;
        }

        public Criteria andKfNoteIsNotNull() {
            addCriterion("kf_note is not null");
            return (Criteria) this;
        }

        public Criteria andKfNoteEqualTo(String value) {
            addCriterion("kf_note =", value, "kfNote");
            return (Criteria) this;
        }

        public Criteria andKfNoteNotEqualTo(String value) {
            addCriterion("kf_note <>", value, "kfNote");
            return (Criteria) this;
        }

        public Criteria andKfNoteGreaterThan(String value) {
            addCriterion("kf_note >", value, "kfNote");
            return (Criteria) this;
        }

        public Criteria andKfNoteGreaterThanOrEqualTo(String value) {
            addCriterion("kf_note >=", value, "kfNote");
            return (Criteria) this;
        }

        public Criteria andKfNoteLessThan(String value) {
            addCriterion("kf_note <", value, "kfNote");
            return (Criteria) this;
        }

        public Criteria andKfNoteLessThanOrEqualTo(String value) {
            addCriterion("kf_note <=", value, "kfNote");
            return (Criteria) this;
        }

        public Criteria andKfNoteLike(String value) {
            addCriterion("kf_note like", value, "kfNote");
            return (Criteria) this;
        }

        public Criteria andKfNoteNotLike(String value) {
            addCriterion("kf_note not like", value, "kfNote");
            return (Criteria) this;
        }

        public Criteria andKfNoteIn(List<String> values) {
            addCriterion("kf_note in", values, "kfNote");
            return (Criteria) this;
        }

        public Criteria andKfNoteNotIn(List<String> values) {
            addCriterion("kf_note not in", values, "kfNote");
            return (Criteria) this;
        }

        public Criteria andKfNoteBetween(String value1, String value2) {
            addCriterion("kf_note between", value1, value2, "kfNote");
            return (Criteria) this;
        }

        public Criteria andKfNoteNotBetween(String value1, String value2) {
            addCriterion("kf_note not between", value1, value2, "kfNote");
            return (Criteria) this;
        }

        public Criteria andPackageIdIsNull() {
            addCriterion("package_id is null");
            return (Criteria) this;
        }

        public Criteria andPackageIdIsNotNull() {
            addCriterion("package_id is not null");
            return (Criteria) this;
        }

        public Criteria andPackageIdEqualTo(Integer value) {
            addCriterion("package_id =", value, "packageId");
            return (Criteria) this;
        }

        public Criteria andPackageIdNotEqualTo(Integer value) {
            addCriterion("package_id <>", value, "packageId");
            return (Criteria) this;
        }

        public Criteria andPackageIdGreaterThan(Integer value) {
            addCriterion("package_id >", value, "packageId");
            return (Criteria) this;
        }

        public Criteria andPackageIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("package_id >=", value, "packageId");
            return (Criteria) this;
        }

        public Criteria andPackageIdLessThan(Integer value) {
            addCriterion("package_id <", value, "packageId");
            return (Criteria) this;
        }

        public Criteria andPackageIdLessThanOrEqualTo(Integer value) {
            addCriterion("package_id <=", value, "packageId");
            return (Criteria) this;
        }

        public Criteria andPackageIdIn(List<Integer> values) {
            addCriterion("package_id in", values, "packageId");
            return (Criteria) this;
        }

        public Criteria andPackageIdNotIn(List<Integer> values) {
            addCriterion("package_id not in", values, "packageId");
            return (Criteria) this;
        }

        public Criteria andPackageIdBetween(Integer value1, Integer value2) {
            addCriterion("package_id between", value1, value2, "packageId");
            return (Criteria) this;
        }

        public Criteria andPackageIdNotBetween(Integer value1, Integer value2) {
            addCriterion("package_id not between", value1, value2, "packageId");
            return (Criteria) this;
        }

        public Criteria andPackageInfoIsNull() {
            addCriterion("package_info is null");
            return (Criteria) this;
        }

        public Criteria andPackageInfoIsNotNull() {
            addCriterion("package_info is not null");
            return (Criteria) this;
        }

        public Criteria andPackageInfoEqualTo(String value) {
            addCriterion("package_info =", value, "packageInfo");
            return (Criteria) this;
        }

        public Criteria andPackageInfoNotEqualTo(String value) {
            addCriterion("package_info <>", value, "packageInfo");
            return (Criteria) this;
        }

        public Criteria andPackageInfoGreaterThan(String value) {
            addCriterion("package_info >", value, "packageInfo");
            return (Criteria) this;
        }

        public Criteria andPackageInfoGreaterThanOrEqualTo(String value) {
            addCriterion("package_info >=", value, "packageInfo");
            return (Criteria) this;
        }

        public Criteria andPackageInfoLessThan(String value) {
            addCriterion("package_info <", value, "packageInfo");
            return (Criteria) this;
        }

        public Criteria andPackageInfoLessThanOrEqualTo(String value) {
            addCriterion("package_info <=", value, "packageInfo");
            return (Criteria) this;
        }

        public Criteria andPackageInfoLike(String value) {
            addCriterion("package_info like", value, "packageInfo");
            return (Criteria) this;
        }

        public Criteria andPackageInfoNotLike(String value) {
            addCriterion("package_info not like", value, "packageInfo");
            return (Criteria) this;
        }

        public Criteria andPackageInfoIn(List<String> values) {
            addCriterion("package_info in", values, "packageInfo");
            return (Criteria) this;
        }

        public Criteria andPackageInfoNotIn(List<String> values) {
            addCriterion("package_info not in", values, "packageInfo");
            return (Criteria) this;
        }

        public Criteria andPackageInfoBetween(String value1, String value2) {
            addCriterion("package_info between", value1, value2, "packageInfo");
            return (Criteria) this;
        }

        public Criteria andPackageInfoNotBetween(String value1, String value2) {
            addCriterion("package_info not between", value1, value2, "packageInfo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_server
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_server
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}