package com.qccr.sh.domain;

import java.math.BigDecimal;

public class OrderGoods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.order_id
     *
     * @mbggenerated
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.goods_id
     *
     * @mbggenerated
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.gift_ogid
     *
     * @mbggenerated
     */
    private Long giftOgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.goods_name
     *
     * @mbggenerated
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.market_cost
     *
     * @mbggenerated
     */
    private BigDecimal marketCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.sale_cost
     *
     * @mbggenerated
     */
    private BigDecimal saleCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.sale_num
     *
     * @mbggenerated
     */
    private Integer saleNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.refund_num
     *
     * @mbggenerated
     */
    private Integer refundNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.refund_sum
     *
     * @mbggenerated
     */
    private BigDecimal refundSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.img
     *
     * @mbggenerated
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.ext_desc
     *
     * @mbggenerated
     */
    private String extDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.merch_id
     *
     * @mbggenerated
     */
    private String merchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.package_id
     *
     * @mbggenerated
     */
    private Integer packageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.package_info
     *
     * @mbggenerated
     */
    private String packageInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.id
     *
     * @return the value of order_goods.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.id
     *
     * @param id the value for order_goods.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.order_id
     *
     * @return the value of order_goods.order_id
     *
     * @mbggenerated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.order_id
     *
     * @param orderId the value for order_goods.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.goods_id
     *
     * @return the value of order_goods.goods_id
     *
     * @mbggenerated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.goods_id
     *
     * @param goodsId the value for order_goods.goods_id
     *
     * @mbggenerated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.gift_ogid
     *
     * @return the value of order_goods.gift_ogid
     *
     * @mbggenerated
     */
    public Long getGiftOgid() {
        return giftOgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.gift_ogid
     *
     * @param giftOgid the value for order_goods.gift_ogid
     *
     * @mbggenerated
     */
    public void setGiftOgid(Long giftOgid) {
        this.giftOgid = giftOgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.goods_name
     *
     * @return the value of order_goods.goods_name
     *
     * @mbggenerated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.goods_name
     *
     * @param goodsName the value for order_goods.goods_name
     *
     * @mbggenerated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.market_cost
     *
     * @return the value of order_goods.market_cost
     *
     * @mbggenerated
     */
    public BigDecimal getMarketCost() {
        return marketCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.market_cost
     *
     * @param marketCost the value for order_goods.market_cost
     *
     * @mbggenerated
     */
    public void setMarketCost(BigDecimal marketCost) {
        this.marketCost = marketCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.sale_cost
     *
     * @return the value of order_goods.sale_cost
     *
     * @mbggenerated
     */
    public BigDecimal getSaleCost() {
        return saleCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.sale_cost
     *
     * @param saleCost the value for order_goods.sale_cost
     *
     * @mbggenerated
     */
    public void setSaleCost(BigDecimal saleCost) {
        this.saleCost = saleCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.sale_num
     *
     * @return the value of order_goods.sale_num
     *
     * @mbggenerated
     */
    public Integer getSaleNum() {
        return saleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.sale_num
     *
     * @param saleNum the value for order_goods.sale_num
     *
     * @mbggenerated
     */
    public void setSaleNum(Integer saleNum) {
        this.saleNum = saleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.status
     *
     * @return the value of order_goods.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.status
     *
     * @param status the value for order_goods.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.refund_num
     *
     * @return the value of order_goods.refund_num
     *
     * @mbggenerated
     */
    public Integer getRefundNum() {
        return refundNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.refund_num
     *
     * @param refundNum the value for order_goods.refund_num
     *
     * @mbggenerated
     */
    public void setRefundNum(Integer refundNum) {
        this.refundNum = refundNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.refund_sum
     *
     * @return the value of order_goods.refund_sum
     *
     * @mbggenerated
     */
    public BigDecimal getRefundSum() {
        return refundSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.refund_sum
     *
     * @param refundSum the value for order_goods.refund_sum
     *
     * @mbggenerated
     */
    public void setRefundSum(BigDecimal refundSum) {
        this.refundSum = refundSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.img
     *
     * @return the value of order_goods.img
     *
     * @mbggenerated
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.img
     *
     * @param img the value for order_goods.img
     *
     * @mbggenerated
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.ext_desc
     *
     * @return the value of order_goods.ext_desc
     *
     * @mbggenerated
     */
    public String getExtDesc() {
        return extDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.ext_desc
     *
     * @param extDesc the value for order_goods.ext_desc
     *
     * @mbggenerated
     */
    public void setExtDesc(String extDesc) {
        this.extDesc = extDesc == null ? null : extDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.merch_id
     *
     * @return the value of order_goods.merch_id
     *
     * @mbggenerated
     */
    public String getMerchId() {
        return merchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.merch_id
     *
     * @param merchId the value for order_goods.merch_id
     *
     * @mbggenerated
     */
    public void setMerchId(String merchId) {
        this.merchId = merchId == null ? null : merchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.package_id
     *
     * @return the value of order_goods.package_id
     *
     * @mbggenerated
     */
    public Integer getPackageId() {
        return packageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.package_id
     *
     * @param packageId the value for order_goods.package_id
     *
     * @mbggenerated
     */
    public void setPackageId(Integer packageId) {
        this.packageId = packageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.package_info
     *
     * @return the value of order_goods.package_info
     *
     * @mbggenerated
     */
    public String getPackageInfo() {
        return packageInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.package_info
     *
     * @param packageInfo the value for order_goods.package_info
     *
     * @mbggenerated
     */
    public void setPackageInfo(String packageInfo) {
        this.packageInfo = packageInfo == null ? null : packageInfo.trim();
    }
}