package com.qccr.sh.domain;

public class TMerchandise {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmerchandise.pkid
     *
     * @mbggenerated
     */
    private Integer pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmerchandise.fenlei
     *
     * @mbggenerated
     */
    private Integer fenlei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmerchandise.store_id
     *
     * @mbggenerated
     */
    private Integer storeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmerchandise.storename
     *
     * @mbggenerated
     */
    private String storename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmerchandise.contract
     *
     * @mbggenerated
     */
    private Integer contract;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmerchandise.onefenlei
     *
     * @mbggenerated
     */
    private Integer onefenlei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmerchandise.twofenlei
     *
     * @mbggenerated
     */
    private Integer twofenlei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmerchandise.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmerchandise.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmerchandise.isrefund
     *
     * @mbggenerated
     */
    private Integer isrefund;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmerchandise.orig_price
     *
     * @mbggenerated
     */
    private Float origPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmerchandise.off_price
     *
     * @mbggenerated
     */
    private Float offPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmerchandise.sprice
     *
     * @mbggenerated
     */
    private Float sprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmerchandise.isagreement
     *
     * @mbggenerated
     */
    private Integer isagreement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmerchandise.st_desc
     *
     * @mbggenerated
     */
    private String stDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmerchandise.attachment
     *
     * @mbggenerated
     */
    private String attachment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmerchandise.image
     *
     * @mbggenerated
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmerchandise.isseckill
     *
     * @mbggenerated
     */
    private Integer isseckill;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmerchandise.ispurchase
     *
     * @mbggenerated
     */
    private Integer ispurchase;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmerchandise.count
     *
     * @mbggenerated
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmerchandise.salestarttime
     *
     * @mbggenerated
     */
    private String salestarttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmerchandise.saleendtime
     *
     * @mbggenerated
     */
    private String saleendtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmerchandise.vstarttime
     *
     * @mbggenerated
     */
    private String vstarttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmerchandise.vendtime
     *
     * @mbggenerated
     */
    private String vendtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmerchandise.createby
     *
     * @mbggenerated
     */
    private String createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmerchandise.createdate
     *
     * @mbggenerated
     */
    private String createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmerchandise.contractname
     *
     * @mbggenerated
     */
    private String contractname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmerchandise.pkid
     *
     * @return the value of tmerchandise.pkid
     *
     * @mbggenerated
     */
    public Integer getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmerchandise.pkid
     *
     * @param pkid the value for tmerchandise.pkid
     *
     * @mbggenerated
     */
    public void setPkid(Integer pkid) {
        this.pkid = pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmerchandise.fenlei
     *
     * @return the value of tmerchandise.fenlei
     *
     * @mbggenerated
     */
    public Integer getFenlei() {
        return fenlei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmerchandise.fenlei
     *
     * @param fenlei the value for tmerchandise.fenlei
     *
     * @mbggenerated
     */
    public void setFenlei(Integer fenlei) {
        this.fenlei = fenlei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmerchandise.store_id
     *
     * @return the value of tmerchandise.store_id
     *
     * @mbggenerated
     */
    public Integer getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmerchandise.store_id
     *
     * @param storeId the value for tmerchandise.store_id
     *
     * @mbggenerated
     */
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmerchandise.storename
     *
     * @return the value of tmerchandise.storename
     *
     * @mbggenerated
     */
    public String getStorename() {
        return storename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmerchandise.storename
     *
     * @param storename the value for tmerchandise.storename
     *
     * @mbggenerated
     */
    public void setStorename(String storename) {
        this.storename = storename == null ? null : storename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmerchandise.contract
     *
     * @return the value of tmerchandise.contract
     *
     * @mbggenerated
     */
    public Integer getContract() {
        return contract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmerchandise.contract
     *
     * @param contract the value for tmerchandise.contract
     *
     * @mbggenerated
     */
    public void setContract(Integer contract) {
        this.contract = contract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmerchandise.onefenlei
     *
     * @return the value of tmerchandise.onefenlei
     *
     * @mbggenerated
     */
    public Integer getOnefenlei() {
        return onefenlei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmerchandise.onefenlei
     *
     * @param onefenlei the value for tmerchandise.onefenlei
     *
     * @mbggenerated
     */
    public void setOnefenlei(Integer onefenlei) {
        this.onefenlei = onefenlei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmerchandise.twofenlei
     *
     * @return the value of tmerchandise.twofenlei
     *
     * @mbggenerated
     */
    public Integer getTwofenlei() {
        return twofenlei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmerchandise.twofenlei
     *
     * @param twofenlei the value for tmerchandise.twofenlei
     *
     * @mbggenerated
     */
    public void setTwofenlei(Integer twofenlei) {
        this.twofenlei = twofenlei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmerchandise.name
     *
     * @return the value of tmerchandise.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmerchandise.name
     *
     * @param name the value for tmerchandise.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmerchandise.status
     *
     * @return the value of tmerchandise.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmerchandise.status
     *
     * @param status the value for tmerchandise.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmerchandise.isrefund
     *
     * @return the value of tmerchandise.isrefund
     *
     * @mbggenerated
     */
    public Integer getIsrefund() {
        return isrefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmerchandise.isrefund
     *
     * @param isrefund the value for tmerchandise.isrefund
     *
     * @mbggenerated
     */
    public void setIsrefund(Integer isrefund) {
        this.isrefund = isrefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmerchandise.orig_price
     *
     * @return the value of tmerchandise.orig_price
     *
     * @mbggenerated
     */
    public Float getOrigPrice() {
        return origPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmerchandise.orig_price
     *
     * @param origPrice the value for tmerchandise.orig_price
     *
     * @mbggenerated
     */
    public void setOrigPrice(Float origPrice) {
        this.origPrice = origPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmerchandise.off_price
     *
     * @return the value of tmerchandise.off_price
     *
     * @mbggenerated
     */
    public Float getOffPrice() {
        return offPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmerchandise.off_price
     *
     * @param offPrice the value for tmerchandise.off_price
     *
     * @mbggenerated
     */
    public void setOffPrice(Float offPrice) {
        this.offPrice = offPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmerchandise.sprice
     *
     * @return the value of tmerchandise.sprice
     *
     * @mbggenerated
     */
    public Float getSprice() {
        return sprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmerchandise.sprice
     *
     * @param sprice the value for tmerchandise.sprice
     *
     * @mbggenerated
     */
    public void setSprice(Float sprice) {
        this.sprice = sprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmerchandise.isagreement
     *
     * @return the value of tmerchandise.isagreement
     *
     * @mbggenerated
     */
    public Integer getIsagreement() {
        return isagreement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmerchandise.isagreement
     *
     * @param isagreement the value for tmerchandise.isagreement
     *
     * @mbggenerated
     */
    public void setIsagreement(Integer isagreement) {
        this.isagreement = isagreement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmerchandise.st_desc
     *
     * @return the value of tmerchandise.st_desc
     *
     * @mbggenerated
     */
    public String getStDesc() {
        return stDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmerchandise.st_desc
     *
     * @param stDesc the value for tmerchandise.st_desc
     *
     * @mbggenerated
     */
    public void setStDesc(String stDesc) {
        this.stDesc = stDesc == null ? null : stDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmerchandise.attachment
     *
     * @return the value of tmerchandise.attachment
     *
     * @mbggenerated
     */
    public String getAttachment() {
        return attachment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmerchandise.attachment
     *
     * @param attachment the value for tmerchandise.attachment
     *
     * @mbggenerated
     */
    public void setAttachment(String attachment) {
        this.attachment = attachment == null ? null : attachment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmerchandise.image
     *
     * @return the value of tmerchandise.image
     *
     * @mbggenerated
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmerchandise.image
     *
     * @param image the value for tmerchandise.image
     *
     * @mbggenerated
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmerchandise.isseckill
     *
     * @return the value of tmerchandise.isseckill
     *
     * @mbggenerated
     */
    public Integer getIsseckill() {
        return isseckill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmerchandise.isseckill
     *
     * @param isseckill the value for tmerchandise.isseckill
     *
     * @mbggenerated
     */
    public void setIsseckill(Integer isseckill) {
        this.isseckill = isseckill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmerchandise.ispurchase
     *
     * @return the value of tmerchandise.ispurchase
     *
     * @mbggenerated
     */
    public Integer getIspurchase() {
        return ispurchase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmerchandise.ispurchase
     *
     * @param ispurchase the value for tmerchandise.ispurchase
     *
     * @mbggenerated
     */
    public void setIspurchase(Integer ispurchase) {
        this.ispurchase = ispurchase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmerchandise.count
     *
     * @return the value of tmerchandise.count
     *
     * @mbggenerated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmerchandise.count
     *
     * @param count the value for tmerchandise.count
     *
     * @mbggenerated
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmerchandise.salestarttime
     *
     * @return the value of tmerchandise.salestarttime
     *
     * @mbggenerated
     */
    public String getSalestarttime() {
        return salestarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmerchandise.salestarttime
     *
     * @param salestarttime the value for tmerchandise.salestarttime
     *
     * @mbggenerated
     */
    public void setSalestarttime(String salestarttime) {
        this.salestarttime = salestarttime == null ? null : salestarttime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmerchandise.saleendtime
     *
     * @return the value of tmerchandise.saleendtime
     *
     * @mbggenerated
     */
    public String getSaleendtime() {
        return saleendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmerchandise.saleendtime
     *
     * @param saleendtime the value for tmerchandise.saleendtime
     *
     * @mbggenerated
     */
    public void setSaleendtime(String saleendtime) {
        this.saleendtime = saleendtime == null ? null : saleendtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmerchandise.vstarttime
     *
     * @return the value of tmerchandise.vstarttime
     *
     * @mbggenerated
     */
    public String getVstarttime() {
        return vstarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmerchandise.vstarttime
     *
     * @param vstarttime the value for tmerchandise.vstarttime
     *
     * @mbggenerated
     */
    public void setVstarttime(String vstarttime) {
        this.vstarttime = vstarttime == null ? null : vstarttime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmerchandise.vendtime
     *
     * @return the value of tmerchandise.vendtime
     *
     * @mbggenerated
     */
    public String getVendtime() {
        return vendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmerchandise.vendtime
     *
     * @param vendtime the value for tmerchandise.vendtime
     *
     * @mbggenerated
     */
    public void setVendtime(String vendtime) {
        this.vendtime = vendtime == null ? null : vendtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmerchandise.createby
     *
     * @return the value of tmerchandise.createby
     *
     * @mbggenerated
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmerchandise.createby
     *
     * @param createby the value for tmerchandise.createby
     *
     * @mbggenerated
     */
    public void setCreateby(String createby) {
        this.createby = createby == null ? null : createby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmerchandise.createdate
     *
     * @return the value of tmerchandise.createdate
     *
     * @mbggenerated
     */
    public String getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmerchandise.createdate
     *
     * @param createdate the value for tmerchandise.createdate
     *
     * @mbggenerated
     */
    public void setCreatedate(String createdate) {
        this.createdate = createdate == null ? null : createdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmerchandise.contractname
     *
     * @return the value of tmerchandise.contractname
     *
     * @mbggenerated
     */
    public String getContractname() {
        return contractname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmerchandise.contractname
     *
     * @param contractname the value for tmerchandise.contractname
     *
     * @mbggenerated
     */
    public void setContractname(String contractname) {
        this.contractname = contractname == null ? null : contractname.trim();
    }
}