package com.qccr.sh.domain;

import java.math.BigDecimal;
import java.util.Date;

public class TStore {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstore.pkid
     *
     * @mbggenerated
     */
    private Integer pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstore.store_name
     *
     * @mbggenerated
     */
    private String storeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstore.store_tel
     *
     * @mbggenerated
     */
    private String storeTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstore.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstore.provinces
     *
     * @mbggenerated
     */
    private Integer provinces;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstore.store_mobile
     *
     * @mbggenerated
     */
    private String storeMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstore.store_lat
     *
     * @mbggenerated
     */
    private BigDecimal storeLat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstore.store_lng
     *
     * @mbggenerated
     */
    private BigDecimal storeLng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstore.office_time
     *
     * @mbggenerated
     */
    private String officeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstore.iswifi
     *
     * @mbggenerated
     */
    private Integer iswifi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstore.iscard
     *
     * @mbggenerated
     */
    private Integer iscard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstore.account_no
     *
     * @mbggenerated
     */
    private String accountNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstore.img_url
     *
     * @mbggenerated
     */
    private String imgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstore.store_owner
     *
     * @mbggenerated
     */
    private String storeOwner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstore.linktel
     *
     * @mbggenerated
     */
    private String linktel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstore.district
     *
     * @mbggenerated
     */
    private String district;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstore.introduction
     *
     * @mbggenerated
     */
    private String introduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstore.store_add
     *
     * @mbggenerated
     */
    private String storeAdd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstore.subway
     *
     * @mbggenerated
     */
    private String subway;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstore.bus
     *
     * @mbggenerated
     */
    private String bus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstore.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstore.memorialday
     *
     * @mbggenerated
     */
    private String memorialday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstore.gmt_modified
     *
     * @mbggenerated
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstore.last_changger
     *
     * @mbggenerated
     */
    private Integer lastChangger;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstore.city
     *
     * @mbggenerated
     */
    private Integer city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstore.area_id
     *
     * @mbggenerated
     */
    private Integer areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstore.merchantid
     *
     * @mbggenerated
     */
    private Integer merchantid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstore.merchantname
     *
     * @mbggenerated
     */
    private String merchantname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstore.corporation
     *
     * @mbggenerated
     */
    private String corporation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstore.certificatetype
     *
     * @mbggenerated
     */
    private Integer certificatetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstore.certificateno
     *
     * @mbggenerated
     */
    private String certificateno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstore.license
     *
     * @mbggenerated
     */
    private String license;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstore.iscommonwash
     *
     * @mbggenerated
     */
    private Integer iscommonwash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstore.isfinewash
     *
     * @mbggenerated
     */
    private Integer isfinewash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstore.carnum
     *
     * @mbggenerated
     */
    private Integer carnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstore.iscosmetology
     *
     * @mbggenerated
     */
    private Integer iscosmetology;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstore.ismaintenance
     *
     * @mbggenerated
     */
    private Integer ismaintenance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstore.istire
     *
     * @mbggenerated
     */
    private Integer istire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstore.payee
     *
     * @mbggenerated
     */
    private String payee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstore.accounttype
     *
     * @mbggenerated
     */
    private Integer accounttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstore.alipay_account
     *
     * @mbggenerated
     */
    private String alipayAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstore.op_bank
     *
     * @mbggenerated
     */
    private String opBank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstore.branchbank
     *
     * @mbggenerated
     */
    private String branchbank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstore.payeeprovince
     *
     * @mbggenerated
     */
    private String payeeprovince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstore.payeecity
     *
     * @mbggenerated
     */
    private String payeecity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstore.storeorigin
     *
     * @mbggenerated
     */
    private Integer storeorigin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstore.cooprate
     *
     * @mbggenerated
     */
    private Integer cooprate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstore.company_id
     *
     * @mbggenerated
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstore.is_delete
     *
     * @mbggenerated
     */
    private String isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstore.image
     *
     * @mbggenerated
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstore.owner
     *
     * @mbggenerated
     */
    private Integer owner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tstore.is_marketable
     *
     * @mbggenerated
     */
    private Boolean isMarketable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstore.pkid
     *
     * @return the value of tstore.pkid
     *
     * @mbggenerated
     */
    public Integer getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstore.pkid
     *
     * @param pkid the value for tstore.pkid
     *
     * @mbggenerated
     */
    public void setPkid(Integer pkid) {
        this.pkid = pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstore.store_name
     *
     * @return the value of tstore.store_name
     *
     * @mbggenerated
     */
    public String getStoreName() {
        return storeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstore.store_name
     *
     * @param storeName the value for tstore.store_name
     *
     * @mbggenerated
     */
    public void setStoreName(String storeName) {
        this.storeName = storeName == null ? null : storeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstore.store_tel
     *
     * @return the value of tstore.store_tel
     *
     * @mbggenerated
     */
    public String getStoreTel() {
        return storeTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstore.store_tel
     *
     * @param storeTel the value for tstore.store_tel
     *
     * @mbggenerated
     */
    public void setStoreTel(String storeTel) {
        this.storeTel = storeTel == null ? null : storeTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstore.status
     *
     * @return the value of tstore.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstore.status
     *
     * @param status the value for tstore.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstore.provinces
     *
     * @return the value of tstore.provinces
     *
     * @mbggenerated
     */
    public Integer getProvinces() {
        return provinces;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstore.provinces
     *
     * @param provinces the value for tstore.provinces
     *
     * @mbggenerated
     */
    public void setProvinces(Integer provinces) {
        this.provinces = provinces;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstore.store_mobile
     *
     * @return the value of tstore.store_mobile
     *
     * @mbggenerated
     */
    public String getStoreMobile() {
        return storeMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstore.store_mobile
     *
     * @param storeMobile the value for tstore.store_mobile
     *
     * @mbggenerated
     */
    public void setStoreMobile(String storeMobile) {
        this.storeMobile = storeMobile == null ? null : storeMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstore.store_lat
     *
     * @return the value of tstore.store_lat
     *
     * @mbggenerated
     */
    public BigDecimal getStoreLat() {
        return storeLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstore.store_lat
     *
     * @param storeLat the value for tstore.store_lat
     *
     * @mbggenerated
     */
    public void setStoreLat(BigDecimal storeLat) {
        this.storeLat = storeLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstore.store_lng
     *
     * @return the value of tstore.store_lng
     *
     * @mbggenerated
     */
    public BigDecimal getStoreLng() {
        return storeLng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstore.store_lng
     *
     * @param storeLng the value for tstore.store_lng
     *
     * @mbggenerated
     */
    public void setStoreLng(BigDecimal storeLng) {
        this.storeLng = storeLng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstore.office_time
     *
     * @return the value of tstore.office_time
     *
     * @mbggenerated
     */
    public String getOfficeTime() {
        return officeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstore.office_time
     *
     * @param officeTime the value for tstore.office_time
     *
     * @mbggenerated
     */
    public void setOfficeTime(String officeTime) {
        this.officeTime = officeTime == null ? null : officeTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstore.iswifi
     *
     * @return the value of tstore.iswifi
     *
     * @mbggenerated
     */
    public Integer getIswifi() {
        return iswifi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstore.iswifi
     *
     * @param iswifi the value for tstore.iswifi
     *
     * @mbggenerated
     */
    public void setIswifi(Integer iswifi) {
        this.iswifi = iswifi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstore.iscard
     *
     * @return the value of tstore.iscard
     *
     * @mbggenerated
     */
    public Integer getIscard() {
        return iscard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstore.iscard
     *
     * @param iscard the value for tstore.iscard
     *
     * @mbggenerated
     */
    public void setIscard(Integer iscard) {
        this.iscard = iscard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstore.account_no
     *
     * @return the value of tstore.account_no
     *
     * @mbggenerated
     */
    public String getAccountNo() {
        return accountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstore.account_no
     *
     * @param accountNo the value for tstore.account_no
     *
     * @mbggenerated
     */
    public void setAccountNo(String accountNo) {
        this.accountNo = accountNo == null ? null : accountNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstore.img_url
     *
     * @return the value of tstore.img_url
     *
     * @mbggenerated
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstore.img_url
     *
     * @param imgUrl the value for tstore.img_url
     *
     * @mbggenerated
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstore.store_owner
     *
     * @return the value of tstore.store_owner
     *
     * @mbggenerated
     */
    public String getStoreOwner() {
        return storeOwner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstore.store_owner
     *
     * @param storeOwner the value for tstore.store_owner
     *
     * @mbggenerated
     */
    public void setStoreOwner(String storeOwner) {
        this.storeOwner = storeOwner == null ? null : storeOwner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstore.linktel
     *
     * @return the value of tstore.linktel
     *
     * @mbggenerated
     */
    public String getLinktel() {
        return linktel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstore.linktel
     *
     * @param linktel the value for tstore.linktel
     *
     * @mbggenerated
     */
    public void setLinktel(String linktel) {
        this.linktel = linktel == null ? null : linktel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstore.district
     *
     * @return the value of tstore.district
     *
     * @mbggenerated
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstore.district
     *
     * @param district the value for tstore.district
     *
     * @mbggenerated
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstore.introduction
     *
     * @return the value of tstore.introduction
     *
     * @mbggenerated
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstore.introduction
     *
     * @param introduction the value for tstore.introduction
     *
     * @mbggenerated
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstore.store_add
     *
     * @return the value of tstore.store_add
     *
     * @mbggenerated
     */
    public String getStoreAdd() {
        return storeAdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstore.store_add
     *
     * @param storeAdd the value for tstore.store_add
     *
     * @mbggenerated
     */
    public void setStoreAdd(String storeAdd) {
        this.storeAdd = storeAdd == null ? null : storeAdd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstore.subway
     *
     * @return the value of tstore.subway
     *
     * @mbggenerated
     */
    public String getSubway() {
        return subway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstore.subway
     *
     * @param subway the value for tstore.subway
     *
     * @mbggenerated
     */
    public void setSubway(String subway) {
        this.subway = subway == null ? null : subway.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstore.bus
     *
     * @return the value of tstore.bus
     *
     * @mbggenerated
     */
    public String getBus() {
        return bus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstore.bus
     *
     * @param bus the value for tstore.bus
     *
     * @mbggenerated
     */
    public void setBus(String bus) {
        this.bus = bus == null ? null : bus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstore.remark
     *
     * @return the value of tstore.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstore.remark
     *
     * @param remark the value for tstore.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstore.memorialday
     *
     * @return the value of tstore.memorialday
     *
     * @mbggenerated
     */
    public String getMemorialday() {
        return memorialday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstore.memorialday
     *
     * @param memorialday the value for tstore.memorialday
     *
     * @mbggenerated
     */
    public void setMemorialday(String memorialday) {
        this.memorialday = memorialday == null ? null : memorialday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstore.gmt_modified
     *
     * @return the value of tstore.gmt_modified
     *
     * @mbggenerated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstore.gmt_modified
     *
     * @param gmtModified the value for tstore.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstore.last_changger
     *
     * @return the value of tstore.last_changger
     *
     * @mbggenerated
     */
    public Integer getLastChangger() {
        return lastChangger;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstore.last_changger
     *
     * @param lastChangger the value for tstore.last_changger
     *
     * @mbggenerated
     */
    public void setLastChangger(Integer lastChangger) {
        this.lastChangger = lastChangger;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstore.city
     *
     * @return the value of tstore.city
     *
     * @mbggenerated
     */
    public Integer getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstore.city
     *
     * @param city the value for tstore.city
     *
     * @mbggenerated
     */
    public void setCity(Integer city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstore.area_id
     *
     * @return the value of tstore.area_id
     *
     * @mbggenerated
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstore.area_id
     *
     * @param areaId the value for tstore.area_id
     *
     * @mbggenerated
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstore.merchantid
     *
     * @return the value of tstore.merchantid
     *
     * @mbggenerated
     */
    public Integer getMerchantid() {
        return merchantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstore.merchantid
     *
     * @param merchantid the value for tstore.merchantid
     *
     * @mbggenerated
     */
    public void setMerchantid(Integer merchantid) {
        this.merchantid = merchantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstore.merchantname
     *
     * @return the value of tstore.merchantname
     *
     * @mbggenerated
     */
    public String getMerchantname() {
        return merchantname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstore.merchantname
     *
     * @param merchantname the value for tstore.merchantname
     *
     * @mbggenerated
     */
    public void setMerchantname(String merchantname) {
        this.merchantname = merchantname == null ? null : merchantname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstore.corporation
     *
     * @return the value of tstore.corporation
     *
     * @mbggenerated
     */
    public String getCorporation() {
        return corporation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstore.corporation
     *
     * @param corporation the value for tstore.corporation
     *
     * @mbggenerated
     */
    public void setCorporation(String corporation) {
        this.corporation = corporation == null ? null : corporation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstore.certificatetype
     *
     * @return the value of tstore.certificatetype
     *
     * @mbggenerated
     */
    public Integer getCertificatetype() {
        return certificatetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstore.certificatetype
     *
     * @param certificatetype the value for tstore.certificatetype
     *
     * @mbggenerated
     */
    public void setCertificatetype(Integer certificatetype) {
        this.certificatetype = certificatetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstore.certificateno
     *
     * @return the value of tstore.certificateno
     *
     * @mbggenerated
     */
    public String getCertificateno() {
        return certificateno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstore.certificateno
     *
     * @param certificateno the value for tstore.certificateno
     *
     * @mbggenerated
     */
    public void setCertificateno(String certificateno) {
        this.certificateno = certificateno == null ? null : certificateno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstore.license
     *
     * @return the value of tstore.license
     *
     * @mbggenerated
     */
    public String getLicense() {
        return license;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstore.license
     *
     * @param license the value for tstore.license
     *
     * @mbggenerated
     */
    public void setLicense(String license) {
        this.license = license == null ? null : license.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstore.iscommonwash
     *
     * @return the value of tstore.iscommonwash
     *
     * @mbggenerated
     */
    public Integer getIscommonwash() {
        return iscommonwash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstore.iscommonwash
     *
     * @param iscommonwash the value for tstore.iscommonwash
     *
     * @mbggenerated
     */
    public void setIscommonwash(Integer iscommonwash) {
        this.iscommonwash = iscommonwash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstore.isfinewash
     *
     * @return the value of tstore.isfinewash
     *
     * @mbggenerated
     */
    public Integer getIsfinewash() {
        return isfinewash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstore.isfinewash
     *
     * @param isfinewash the value for tstore.isfinewash
     *
     * @mbggenerated
     */
    public void setIsfinewash(Integer isfinewash) {
        this.isfinewash = isfinewash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstore.carnum
     *
     * @return the value of tstore.carnum
     *
     * @mbggenerated
     */
    public Integer getCarnum() {
        return carnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstore.carnum
     *
     * @param carnum the value for tstore.carnum
     *
     * @mbggenerated
     */
    public void setCarnum(Integer carnum) {
        this.carnum = carnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstore.iscosmetology
     *
     * @return the value of tstore.iscosmetology
     *
     * @mbggenerated
     */
    public Integer getIscosmetology() {
        return iscosmetology;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstore.iscosmetology
     *
     * @param iscosmetology the value for tstore.iscosmetology
     *
     * @mbggenerated
     */
    public void setIscosmetology(Integer iscosmetology) {
        this.iscosmetology = iscosmetology;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstore.ismaintenance
     *
     * @return the value of tstore.ismaintenance
     *
     * @mbggenerated
     */
    public Integer getIsmaintenance() {
        return ismaintenance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstore.ismaintenance
     *
     * @param ismaintenance the value for tstore.ismaintenance
     *
     * @mbggenerated
     */
    public void setIsmaintenance(Integer ismaintenance) {
        this.ismaintenance = ismaintenance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstore.istire
     *
     * @return the value of tstore.istire
     *
     * @mbggenerated
     */
    public Integer getIstire() {
        return istire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstore.istire
     *
     * @param istire the value for tstore.istire
     *
     * @mbggenerated
     */
    public void setIstire(Integer istire) {
        this.istire = istire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstore.payee
     *
     * @return the value of tstore.payee
     *
     * @mbggenerated
     */
    public String getPayee() {
        return payee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstore.payee
     *
     * @param payee the value for tstore.payee
     *
     * @mbggenerated
     */
    public void setPayee(String payee) {
        this.payee = payee == null ? null : payee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstore.accounttype
     *
     * @return the value of tstore.accounttype
     *
     * @mbggenerated
     */
    public Integer getAccounttype() {
        return accounttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstore.accounttype
     *
     * @param accounttype the value for tstore.accounttype
     *
     * @mbggenerated
     */
    public void setAccounttype(Integer accounttype) {
        this.accounttype = accounttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstore.alipay_account
     *
     * @return the value of tstore.alipay_account
     *
     * @mbggenerated
     */
    public String getAlipayAccount() {
        return alipayAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstore.alipay_account
     *
     * @param alipayAccount the value for tstore.alipay_account
     *
     * @mbggenerated
     */
    public void setAlipayAccount(String alipayAccount) {
        this.alipayAccount = alipayAccount == null ? null : alipayAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstore.op_bank
     *
     * @return the value of tstore.op_bank
     *
     * @mbggenerated
     */
    public String getOpBank() {
        return opBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstore.op_bank
     *
     * @param opBank the value for tstore.op_bank
     *
     * @mbggenerated
     */
    public void setOpBank(String opBank) {
        this.opBank = opBank == null ? null : opBank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstore.branchbank
     *
     * @return the value of tstore.branchbank
     *
     * @mbggenerated
     */
    public String getBranchbank() {
        return branchbank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstore.branchbank
     *
     * @param branchbank the value for tstore.branchbank
     *
     * @mbggenerated
     */
    public void setBranchbank(String branchbank) {
        this.branchbank = branchbank == null ? null : branchbank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstore.payeeprovince
     *
     * @return the value of tstore.payeeprovince
     *
     * @mbggenerated
     */
    public String getPayeeprovince() {
        return payeeprovince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstore.payeeprovince
     *
     * @param payeeprovince the value for tstore.payeeprovince
     *
     * @mbggenerated
     */
    public void setPayeeprovince(String payeeprovince) {
        this.payeeprovince = payeeprovince == null ? null : payeeprovince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstore.payeecity
     *
     * @return the value of tstore.payeecity
     *
     * @mbggenerated
     */
    public String getPayeecity() {
        return payeecity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstore.payeecity
     *
     * @param payeecity the value for tstore.payeecity
     *
     * @mbggenerated
     */
    public void setPayeecity(String payeecity) {
        this.payeecity = payeecity == null ? null : payeecity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstore.storeorigin
     *
     * @return the value of tstore.storeorigin
     *
     * @mbggenerated
     */
    public Integer getStoreorigin() {
        return storeorigin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstore.storeorigin
     *
     * @param storeorigin the value for tstore.storeorigin
     *
     * @mbggenerated
     */
    public void setStoreorigin(Integer storeorigin) {
        this.storeorigin = storeorigin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstore.cooprate
     *
     * @return the value of tstore.cooprate
     *
     * @mbggenerated
     */
    public Integer getCooprate() {
        return cooprate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstore.cooprate
     *
     * @param cooprate the value for tstore.cooprate
     *
     * @mbggenerated
     */
    public void setCooprate(Integer cooprate) {
        this.cooprate = cooprate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstore.company_id
     *
     * @return the value of tstore.company_id
     *
     * @mbggenerated
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstore.company_id
     *
     * @param companyId the value for tstore.company_id
     *
     * @mbggenerated
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstore.is_delete
     *
     * @return the value of tstore.is_delete
     *
     * @mbggenerated
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstore.is_delete
     *
     * @param isDelete the value for tstore.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete == null ? null : isDelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstore.image
     *
     * @return the value of tstore.image
     *
     * @mbggenerated
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstore.image
     *
     * @param image the value for tstore.image
     *
     * @mbggenerated
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstore.owner
     *
     * @return the value of tstore.owner
     *
     * @mbggenerated
     */
    public Integer getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstore.owner
     *
     * @param owner the value for tstore.owner
     *
     * @mbggenerated
     */
    public void setOwner(Integer owner) {
        this.owner = owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tstore.is_marketable
     *
     * @return the value of tstore.is_marketable
     *
     * @mbggenerated
     */
    public Boolean getIsMarketable() {
        return isMarketable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tstore.is_marketable
     *
     * @param isMarketable the value for tstore.is_marketable
     *
     * @mbggenerated
     */
    public void setIsMarketable(Boolean isMarketable) {
        this.isMarketable = isMarketable;
    }
}