package com.qccr.sh.mapper;

import com.qccr.sh.domain.Usertrace;
import com.qccr.sh.domain.UsertraceExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface UsertraceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertrace
     *
     * @mbggenerated
     */
    int countByExample(UsertraceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertrace
     *
     * @mbggenerated
     */
    int deleteByExample(UsertraceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertrace
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertrace
     *
     * @mbggenerated
     */
    int insert(Usertrace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertrace
     *
     * @mbggenerated
     */
    int insertSelective(Usertrace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertrace
     *
     * @mbggenerated
     */
    List<Usertrace> selectByExampleWithRowbounds(UsertraceExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertrace
     *
     * @mbggenerated
     */
    List<Usertrace> selectByExample(UsertraceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertrace
     *
     * @mbggenerated
     */
    Usertrace selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertrace
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Usertrace record, @Param("example") UsertraceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertrace
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Usertrace record, @Param("example") UsertraceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertrace
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Usertrace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertrace
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Usertrace record);
}